Requiem Housekeeping
loot/skyrim pull request #464
Opened 2021-05-23 17:01 UTC by Kaenguru-Knobel-Kette

A lot of the Requiem related metadata concerns Requiem 2.0 (or even older versions) which hasn't been supported for 3 years now. Not only does this clutter up the masterlist, but many of the old messages are misleading or flat out wrong when displayed to a user of a recent Requiem version. Due to the sheer amount of possible plugin combinations in Requiem's ecosystem, tweaking all current metadata to be version-specific is a hopeless endeavour even if one were to deem this useful. Similarly, keeping old metadata as legacy support isn't practial either.

Therefore, this PR removes all metadata concerning Requiem 2.0 or older and adds consequent new metdata.

- The warning `patchUnavailable_Requiem` is added to plugins that cause noteworthy compatibility issues and no longer have a compatibility patch available.
- The error `incVersionX` is added to common version mismatches (i.e. I've seen users run into them). This message replaces `versionXIncY` which was originally used in SSE to denote version mismatches between executables and therefore didn't sound quite correct when applied to version mismatches between plugins.
- I took this opportunity to break up [this regex hack](https://github.com/loot/skyrim/blob/1f0e1159ed4e04ae88abf353e6c52b56878144c4/masterlist.yaml#L10785) and instead add manual load afters where strictly necessary because only one of these plugins is still relevant.
- Last but not least, a few missing urls have been added.

2021-05-24 06:31 UTC, sibir-ine requested changes
@Kaenguru-Knobel-Kette It's mostly formatting changes which aren't absolutely necessary, but we'd appreciate if you could implement them to save us time down the line.

There are some changes that we'd really appreciate before merging though, specifically replacing all instances of `*incVersionX` with an `inc` message as I outlined & addressing the message for Improved CloseFaced Helmets that may be erroneous.

I've tried to make as many of them GitHub-registered suggestions as I could to make it easier for you, but apparently deleted lines throw a spanner in the works; you'll have to add some suggestions manually.

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +  - &patchUnavailable_Requiem
Just to keep the masterlists' style consistent, derivative anchors immediately follow their source anchor or other derivatives. Also, anchor names are camel case unless two uppercase letters from two separate words are joined (e.g., `requiresMCM_X`). Not a blocking change though.

```suggestion
  - &patchUnavailableRequiem
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        text: 'This plugin is incompatible with your version of %1%.'
Instead of adding a new message anchor, you could make use of the `inc` key. That way, we won't have to worry about localizing a whole new message. I'll show examples below.

`&versionXIncY` can still be removed though as it's unused now.

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
The merge key (`<<:`) is unnecessary since you're not overwriting any values from the anchor. We also prefer to write single-entry lists in-line to keep the masterlists' style consistent. You can replace it with the following (sorry, GitHub isn't letting me write a proper suggestion since there are deleted lines):

```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
Same as above.

```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
This can be replaced with the following:

```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

The resulting message will be `This plugin is incompatible with "Requiem v3.0.0+", but both are present.`

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```suggestion
      - *patchUnavailableRequiem
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem' ]
```suggestion
      - <<: *patchUnavailableRequiem
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>          subs: [ 'the Requiem patch for Improved Closefaced Helmets' ]
This will cause the message to be displayed as long as Improved Closefaced Helmets is active, regardless of the status of the patch. Does the plugin still need to be deleted with the latest version of the patch, or can this message be removed?

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v4.0.0+'
        condition: 'checksum("Fozars_Dragonborn_-_Requiem_Patch.esp", 0AE44632) and version("Requiem.esp", "4.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v4.0.0+'
        condition: 'version("Requiem.esp", "4.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> -      - 'COR-NoHeavyStormcloaks.esp'
```yaml
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Requiem - Cutting Room Floor.esp'
```suggestion
    after: [ 'Requiem - Cutting Room Floor.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```yaml
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem - Minor Arcana - Roleplaying.esp'
```yaml
    after: [ 'Requiem - Minor Arcana - Roleplaying.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem - Audio Overhaul for Skyrim.esp'
```suggestion
    after: [ 'Requiem - Audio Overhaul for Skyrim.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem - Immersive Sounds Compendium.esp'
```suggestion
    after: [ 'Requiem - Immersive Sounds Compendium.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```yaml
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Requiem - Minor Arcana - Roleplaying.esp'
```suggestion
    after: [ 'Requiem - Minor Arcana - Roleplaying.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Fozars_Dragonborn_-_Requiem_Patch.esp'
```suggestion
    after: [ 'Fozars_Dragonborn_-_Requiem_Patch.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v4.0.0+'
        condition: 'version("Requiem.esp", "4.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v4.0.0+'
        condition: 'version("Requiem.esp", "4.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem_Minor_Arcana.esp'
```yaml
    after: 'Requiem_Minor_Arcana.esp'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>          subs: [ 'Requiem.esp' ]
To keep the masterlists' style consistent, we also prefer to order the `subs` key before the `condition` key.

```suggestion
        subs: [ 'Requiem.esp' ]
        condition: 'active("Requiem.esp")'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v2.0.0+'
        condition: 'version("Requiem.esp", "2.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
msg: [ *patchUnavailableRequiem ]

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
We also order the `inc` key (& the `msg` key for that matter) before the `dirty` key.

```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v2.0.0+'
        condition: 'version("Requiem.esp", "2.0.0", >=)'
    dirty:
      - <<: *dirtyPlugin
        crc: 0xe410b8ec
        itm: 3
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +      - <<: *patchUnavailable_Requiem
```yaml
    msg: [ *patchUnavailableRequiem ]
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```suggestion
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v2.0.0+'
        condition: 'version("Requiem.esp", "2.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'Requiem.esp' ]
```yaml
    inc:
      - name: 'Requiem.esp'
        display: 'Requiem v3.0.0+'
        condition: 'version("Requiem.esp", "3.0.0", >=)'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>          subs: [ 'Requiem - Immersive Horses.esp' ]
```suggestion
        subs: [ 'Requiem - Immersive Horses.esp' ]
        condition: 'active("Requiem - Immersive Horses.esp")'
```

2021-05-24 06:31 UTC, sibir-ine commented on masterlist.yaml
>        - 'Requiem.esp'
```suggestion
    after: [ 'Requiem.esp' ]
```

2021-05-24 08:59 UTC, Kaenguru-Knobel-Kette commented on masterlist.yaml
>          subs: [ 'the Requiem patch for Improved Closefaced Helmets' ]
The message is still relevant, but this should have been `condition: 'active("imp_helm_legend.esp") and active("Requiem - Improved Closefaced Helmets.esp")'`

2021-05-24 09:51 UTC, sibir-ine approved these changes

2021-05-24 09:54 UTC, sibir-ine commented
Looks good to me, but, due to the size, I'd like to give it a day before merging so the rest of the team can take a look & see if anything else got missed.

2021-05-24 10:11 UTC, sibir-ine reviewed
@Kaenguru-Knobel-Kette In the meantime, just a few more minor formatting changes I noticed after another review.

2021-05-24 10:11 UTC, sibir-ine commented on masterlist.yaml
Since `&patchUnavailableRequiem` is derived from `&patchUnavailable`, we prefer it to immediately follow `&patchUnavailable`.

```suggestion
```

2021-05-24 10:11 UTC, sibir-ine commented on masterlist.yaml
> +    after: [ 'Requiem.esp' ]
We prefer to order the `after` key before the `msg` key.

```yaml
    after: [ 'Requiem.esp' ]
    msg:
      - <<: *patch3rdParty_Requiem_SRP
        condition: 'active("Requiem.esp") and not active("Requiem - Sacrosanct Patch.esp")'
```

2021-05-24 13:27 UTC, MacSplody commented
> 
> 
> Looks good to me, but, due to the size, I'd like to give it a day before merging so the rest of the team can take a look & see if anything else got missed.

Looks fine to me.

2021-05-24 13:29 UTC, MacSplody approved these changes

2021-05-25 05:44 UTC, sibir-ine commented
Okay, I'll merge it in a bit.

2021-05-25 09:16 UTC, merged

2021-05-25 09:16 UTC, sibir-ine commented
@Kaenguru-Knobel-Kette Thanks!